# Generated by Django 4.0 on 2022-01-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromiseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Promises',
            },
        ),
    ]
