# Generated by Django 4.0 on 2022-01-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0003_promisemodel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='promisemodel',
            name='fontColor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
